ejercicio/app_ejercicios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuario_app import views as usuario_app_views  # Importa la vista de registro

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario_app/', include('usuario_app.urls')),
]

#maneja los archivos multimedia
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ejercicio/usuario_app/urls.py
from django.urls import path     
from . import views #means that views is in the same directory as this

app_name = 'usuario_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.autenticationView, name='login'),
    path('logout', views.logOutView, name='logout'),
    path('register', views.register, name='register'),
    path('edit', views.editPerfil, name='editPerfil')
]

ejercicio/usuario_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import gettext_lazy as _

class CustomUser(AbstractUser):
    # Campos heredados de AbstractUser
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=20, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    # Campos personalizados
    peso = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    foto_perfil = models.ImageField(upload_to='perfil/', null=True, blank=True)
    groups = models.ManyToManyField(Group, verbose_name=_('groups'), blank=True, related_name='customuser_set')
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        related_name='customuser_set',
        help_text=_('Specific permissions for this user.'),
    )
    birthday = models.DateField(null=True, blank=True)

      # Campo de género
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)


    GOAL_CHOICES = (
        ('Earn weight', _('Earn weight')),
        ('Lose weight', _('Lose weight')),
        ('Physical activity', _('Physical activity')),
    )
    goal = models.CharField(
        max_length=20,
        choices=GOAL_CHOICES,
        default='Earn weight',  # Opción predeterminada
    )
    
    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

    def __str__(self):
        return self.username

ejercicio/usuario_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.auth.forms import AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'peso', 'birthday','gender', 'goal']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'}),
            'gender': forms.RadioSelect(choices=CustomUser.GENDER_CHOICES),
        }

# forms.py en tu aplicación

class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'peso', 'foto_perfil', 'birthday','gender', 'goal']

        # def __init__(self, *args, **kwargs):
        #     super().__init__(*args, **kwargs)
        #     # Eliminamos la opción predeterminada ("---------") del campo 'gender'
        #     self.fields['gender'].empty_label = None
    # widgets = {
    #     'username': forms.TextInput(attrs={'class': 'input--style-4'}),
    #     'first_name': forms.TextInput(attrs={'class': 'input--style-4'}),
    #     'last_name': forms.TextInput(attrs={'class': 'input--style-4'}),
    #     'email': forms.EmailInput(attrs={'class': 'input--style-4'}),
    #     'password1': forms.PasswordInput(attrs={'class': 'input--style-4'}),
    #     'password2': forms.PasswordInput(attrs={'class': 'input--style-4'}),
    #     'peso': forms.TextInput(attrs={'class': 'input--style-4'}),
    #     'foto_perfil': forms.FileInput(attrs={'class': 'input--style-4'}),
    # }

ejercicio/usuario_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm, CustomUserEditForm
from django.contrib.auth.decorators import login_required
from .models import CustomUser



@login_required()
def index(request):
    return render(request,'index.html')


def register(request):
    template_user = reverse_lazy('usuario_app:index')

    if request.user.is_authenticated:
        return HttpResponseRedirect(template_user)
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            # Puedes agregar aquí cualquier lógica adicional, como iniciar sesión automáticamente al usuario
            return HttpResponseRedirect(template_user) # Redirige al usuario a la página de inicio de sesión
        else:
            print(form.errors)
            return render(request, 'register.html',{'form':form.errors})
    else:
        form = CustomUserCreationForm()
        return render(request, 'register.html', {'form': form})

@login_required()
def editPerfil(request):
    if request.method == 'GET':
        user = request.user
        form = CustomUserEditForm(instance=user)
        return render(request, 'register.html', {'form':form})
    
    if request.method == 'POST':
        user = CustomUser.objects.get(username=request.user)
        form = CustomUserEditForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
            return render(request,'index.html')
        else:
            print(form.errors)
            return render(request, 'register.html',{'form':form.errors})
        

def autenticationView(request):
    template_name = 'login.html'
    template_user = reverse_lazy('usuario_app:index')
    
    if request.user.is_authenticated:
        return HttpResponseRedirect(template_user)

    if request.method == 'POST':
       print(request.POST['username'])
       print(request.POST['password'])
       user = authenticate(username=request.POST['username'], password=request.POST['password'])
       print(user)
       if user is not None:
           login(request, user)
           return HttpResponseRedirect(template_user)
       else:
        form = AuthenticationForm()
        return render(request, template_name, {
            'form': form,
            })
        
       
    else:
        form = AuthenticationForm()
        return render(request, template_name, {'form': form})
    

def logOutView(request):
    logout(request)
    
    return HttpResponseRedirect(reverse_lazy('usuario_app:login'))

ejercicio/usuario_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">
    <title>DJANGO POST - {% block titulo %}{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    /> {% block estilos %}{% endblock %}
    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    
    {% block contenido %}
    {% load static %}

<link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
<link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">

<!-- Font special for pages-->
<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Vendor CSS-->
<link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
<link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

<!-- Main CSS-->
<link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">

    
    {% endblock %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

ejercicio/usuario_app/templates/index.html
{% extends "base.html"%}

{% block titulo %}BIENVENIDA{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Bienvenidos a Mi Aplicación</h1>
    <hr>
    Usuario: {{ request.user}}
    <a href="{% url 'usuario_app:logout' %}">Logout</a>
    <a href="{% url 'usuario_app:editPerfil'%}">Edit Perfil</a>
</div>


{% endblock %}

ejercicio/usuario_app/templates/login.html
{% extends "base.html" %}

{% block titulo %}Login{% endblock %}

{% block contenido %}
{% load static %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Login</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row row-space">
                        <div class="col-12">
                            <div class="input-group">
                                <label class="label">Username</label>
                                {{form.username}}
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-12">
                            <div class="input-group">
                                <label class="label">Password</label>
                                {{form.password}}
                            </div>
                        </div>
                    </div>
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--green" type="submit">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ejercicio/usuario_app/templates/register.html
{% extends "base.html" %} {% block titulo %}Login y Register{% endblock %} {% block contenido %} {% load static %}
<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
    <div class="wrapper wrapper--w680">
        <div class="card card-4">
            <div class="card-body">
                <h2 class="title">Registration Form</h2>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">first name</label> {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">last name</label> {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Birthday</label>
                                <div class="input-group-icon">
                                    {{ form.birthday}}
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Gender</label>
                                <div class="p-t-10">
                                    {{ form.gender}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Email</label> {{ form.email }}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Weight (Kg) </label> {{ form.peso }}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">User Name </label> {{ form.username }}
                            </div>
                        </div>
                    </div>
                    <div class="row row-space">
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Password</label> {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <label class="label">Confirm Password</label> {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="input-group">
                        <label class="label">Goal</label>
                        <div class="rs-select2 js-select-simple select--no-search">
                            {{ form.goal }}
                            <div class="select-dropdown"></div>
                        </div>
                    </div>
                    {% if form.foto_perfil%}
                             {{form.foto_perfil}}
                    {% endif %}
                    <div class="p-t-15">
                        <button class="btn btn--radius-2 btn--green" type="submit">Submit</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}